### ISSUE TITLE
TypeError: unhashable type: 'DeviceArray'

### ISSUE THREAD

**Issue by cxw-droid** [nglaze00/path-prediction#3]
Hi, thanks for sharing the code.
When I ran code `python trajectory_experiments.py`, there is an error as follows,
>  File "/home/xyz/code/SCoNe_GCN/trajectory_analysis/trajectory_experiments.py", line 277, in <listcomp>
    n_nbrs = onp.array([len(nbrhoods_dict[n]) for n in last_nodes])
TypeError: unhashable type: 'DeviceArray'

more info:
>type(last_nodes)
<class 'jaxlib.xla_extension.DeviceArray'>
last_nodes.shape
(1000,)

**Comment by nglaze00** [comment]
Sorry about that, should be resolved now -- caused by a typo (np instead of onp on line 236)
