### ISSUE TITLE
test results: STD, REV, TRA, standard test, 2-target accs

### ISSUE THREAD

**Issue by cxw-droid** [nglaze00/path-prediction#4]
Hello, may I ask a few questions on the testing results?

1. The paper table 1 (a) uses `STD, REV, TRA` to show the results, what is the meaning of them? I cannot find it in the paper.
2.  After running `trajectory_experiments.py`, the test shows `standard test set:` and `2-target accs`. What is the meaning of them? Does the `standard test set:` correspond to the `STD` above?

Thanks.

**Comment by nglaze00** [comment]
Thank you for the questions!
1. Sorry about that, I agree that it's unclear in the paper. In Section 6.2, the experiment described under the _Performance_ header corresponds to the STD (standard) table header. Under the _Testing Generalization_ header, we describe testing on reversed flows, and testing on unseen simplicial structures. These correspond to the REV (reversed) and TRA (transfer) table headers, respectively.
2. I believe `standard test set:` does correspond to the STD table header, and `2-target accs:` corresponds to the ratio of samples for which the model predicts the true next node to be more likely than a randomly selected next node (out of the current node's neighborhood). For example, say the true path continues to node A, and we randomly select node B; if the model predicts node C with probability 0.5, node B with probability 0.1, and node A with probability 0.4, this sample would be counted correct under 2-target accuracy (if node C is randomly selected, it would be incorrect, so there is some variance there). I don't believe we ended up including 2-target accuracy in the paper -- it was just something we explored during our research.

Let me know if this answers your questions!
